reconnection:
  frequency: "3000"
  attempts: "3"
  
scheduler:
  frequency: "0 0 0/1 1/1 * ? *"
  startdelay: "0"
  
http:
  host: "0.0.0.0"
  port: "8084"
  timeout: "320000"

os:
  maxentries: "1"
  entryttl: "60"
  expirationinterval: "60"