scheduler:
  frequency: "0 0 0/1 1/1 * ? *"
  startdelay: "0"
  timezone: "IST"

lms-tcdp:
  host : "lms-tcdp-sys-app-ggc1em.smgn5c.sgp-s1.cloudhub.io"
  port: "443"
  clientId: "7cda3089a66e4d9fae77882f753e1266"
  basePath: "/api"
  path: "/tcdp"
  method: "GET"

databricks-employee:
  host: "databricks-all-reports-sys-api-ggc1em.smgn5c.sgp-s1.cloudhub.io"
  port: "443"
  clientId: "50474bee93a2489b9c641bfa6b161f37"
  basePath: "/api"
  path: "/upload"
  method: "POST"



