lms-tcdp:
  clientSecret: "![mrEunsimDNY6TKQCqBRDUHv/1WZnIFj9HfVO7DkyTOG6zuQ/vt31kDSiEciSHjRW]"

databricks-employee:
  clientSecret: "![SgTDGp8OCO7FcK6MDr6w5jn5+5y8XsyGApgUCcOEYyH0rsa26SMm1fDMi2PbtI/M]"