lms-tcdp:
  clientSecret: "![mrEunsimDNY6TKQCqBRDUHv/1WZnIFj9HfVO7DkyTOG6zuQ/vt31kDSiEciSHjRW]"

databricks-employee:
  clientSecret: "![eBznea6GRg8Tudz5C4+XexQi9BtfIg+er0LM/xHwvTwbh6lgnqtkFzLGXjIoPwy1]"